/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.bliblioteca.proyectobasesdedatos.GUI.Crear;

import com.bliblioteca.proyectobasesdedatos.Control.Controlador;
import com.bliblioteca.proyectobasesdedatos.logica.Libro;
import java.awt.Color;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author juan.quevedo
 */
public class CrearLibro extends javax.swing.JPanel {

    /**
     * Creates new form Solicitud
     */
    private DefaultComboBoxModel jCbModelCodEditorial,jcbModelCodArea;
    private String idEempleado;
    private Controlador controlador;
    public CrearLibro(Controlador controlador, String idEmpleado) {
        this.idEempleado = idEmpleado;
        this.controlador = controlador;
        jCbModelCodEditorial = new DefaultComboBoxModel();
        jcbModelCodArea = new DefaultComboBoxModel();
        this.controlador.llenarComboBoxAgregarLibro(jcbModelCodArea, true);
        this.controlador.llenarComboBoxAgregarLibro(jCbModelCodEditorial, false);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        campoAnioPublicacion = new javax.swing.JTextField();
        campoISBN = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        botonCrearLibro = new javax.swing.JButton();
        campoTituloLibro = new javax.swing.JTextField();
        campoNumPaginas = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        campoIdioma = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();

        setPreferredSize(new java.awt.Dimension(460, 430));

        jLabel1.setFont(new java.awt.Font("Yu Gothic", 1, 12)); // NOI18N
        jLabel1.setText("Crear Libro");

        jLabel2.setText("Titulo del libro:");

        jLabel4.setText("Año de publicación:");

        campoAnioPublicacion.setForeground(new java.awt.Color(204, 204, 204));
        campoAnioPublicacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                campoAnioPublicacionMousePressed(evt);
            }
        });
        campoAnioPublicacion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                campoAnioPublicacionKeyReleased(evt);
            }
        });

        campoISBN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoISBNActionPerformed(evt);
            }
        });
        campoISBN.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                campoISBNKeyReleased(evt);
            }
        });

        jLabel5.setText("ISBN del libro:");

        jLabel7.setText("Idioma:");

        botonCrearLibro.setText("Crear");
        botonCrearLibro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonCrearLibroMouseClicked(evt);
            }
        });
        botonCrearLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCrearLibroActionPerformed(evt);
            }
        });

        campoTituloLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoTituloLibroActionPerformed(evt);
            }
        });
        campoTituloLibro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                campoTituloLibroKeyReleased(evt);
            }
        });

        campoNumPaginas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoNumPaginasActionPerformed(evt);
            }
        });

        jLabel8.setText("Número de páginas:");

        campoIdioma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoIdiomaActionPerformed(evt);
            }
        });
        campoIdioma.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                campoIdiomaKeyReleased(evt);
            }
        });

        jLabel9.setText("Código de Área:");

        jLabel10.setText("Código de Editorial:");

        jComboBox1.setModel(jcbModelCodArea);

        jComboBox2.setModel(jCbModelCodEditorial);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(botonCrearLibro, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel1)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(campoISBN, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                            .addComponent(campoAnioPublicacion)
                            .addComponent(campoTituloLibro)
                            .addComponent(campoNumPaginas, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                            .addComponent(campoIdioma, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                            .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(39, 39, 39))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(campoTituloLibro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(campoAnioPublicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoISBN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoNumPaginas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoIdioma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addComponent(botonCrearLibro, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void campoISBNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoISBNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoISBNActionPerformed

    private void botonCrearLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCrearLibroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonCrearLibroActionPerformed

    private void campoTituloLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoTituloLibroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoTituloLibroActionPerformed

    private void campoNumPaginasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoNumPaginasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoNumPaginasActionPerformed

    private void campoIdiomaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoIdiomaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoIdiomaActionPerformed

    private void campoTituloLibroKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoTituloLibroKeyReleased
        String size = campoTituloLibro.getText();
        if(size.length()>100){
            campoTituloLibro.setText("");
            JOptionPane.showMessageDialog(null, "El campo no puede tener mas de 100 caracteres");
        }
    }//GEN-LAST:event_campoTituloLibroKeyReleased

    private void campoAnioPublicacionKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoAnioPublicacionKeyReleased
        
    }//GEN-LAST:event_campoAnioPublicacionKeyReleased

    private void campoISBNKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoISBNKeyReleased
        String size = campoISBN.getText();
        if(size.length()>13){
            campoISBN.setText("");
            JOptionPane.showMessageDialog(null, "El campo no puede tener mas de 13 caracteres");
        }
    }//GEN-LAST:event_campoISBNKeyReleased

    private void campoIdiomaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoIdiomaKeyReleased
        String size = campoIdioma.getText();
        if(size.length()>20){
            campoIdioma.setText("");
            JOptionPane.showMessageDialog(null, "El campo no puede tener mas de 20 caracteres");
        }
    }//GEN-LAST:event_campoIdiomaKeyReleased

    private void botonCrearLibroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonCrearLibroMouseClicked
        if(jComboBox1.getSelectedIndex()==0 || jComboBox2.getSelectedIndex()==0){
            JOptionPane.showMessageDialog(null, "Por favor seleccionar un campo para cod area y/o cod editorial");
        }
        else{
            if(campoTituloLibro.getText().equals("")||campoISBN.getText().equals("") || campoNumPaginas.getText().equals("")||campoIdioma.getText().equals("")){
                JOptionPane.showMessageDialog(null, "Por favor llene todos los campos");
            }
            else{
                String ISBN =campoISBN.getText();
                String codArea = (String) jComboBox1.getSelectedItem();
                String codEditorial = (String) jComboBox2.getSelectedItem();
                String id_empleado = this.idEempleado;
                String tituloLibro = campoTituloLibro.getText();
                if(controlador.esEntero(campoNumPaginas.getText()) &&controlador.esEntero(campoAnioPublicacion.getText())){
                    int nPaginas = Integer.parseInt((String) campoNumPaginas.getText());
                    int anioPubli = Integer.parseInt((String) campoAnioPublicacion.getText());
                    String idioma = campoIdioma.getText();
                    Libro elLibro = new Libro(ISBN, codArea, codEditorial, id_empleado, tituloLibro, anioPubli, nPaginas, idioma);
                    controlador.agregarObjeto(elLibro);
                    JOptionPane.showMessageDialog(null, "Libro agregado con exito");
                    
                }
                else{
                    JOptionPane.showMessageDialog(null, "Numero pagianas y anio deben ser enteros");
                }
            }
        }
    }//GEN-LAST:event_botonCrearLibroMouseClicked

    private void campoAnioPublicacionMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_campoAnioPublicacionMousePressed
        campoAnioPublicacion.setText("");
        campoAnioPublicacion.setBackground(Color.BLACK);
    }//GEN-LAST:event_campoAnioPublicacionMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonCrearLibro;
    private javax.swing.JTextField campoAnioPublicacion;
    private javax.swing.JTextField campoISBN;
    private javax.swing.JTextField campoIdioma;
    private javax.swing.JTextField campoNumPaginas;
    private javax.swing.JTextField campoTituloLibro;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
