/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.bliblioteca.proyectobasesdedatos.GUI.Crear;

import com.bliblioteca.proyectobasesdedatos.Control.Controlador;
import com.bliblioteca.proyectobasesdedatos.logica.Multa;
import com.bliblioteca.proyectobasesdedatos.logica.Solicitud;
import java.awt.Color;
import java.text.ParseException;
import java.util.Date;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author juan.quevedo
 */
public class CrearMulta extends javax.swing.JPanel {

    /**
     * Creates new form Solicitud
     */
    private DefaultComboBoxModel comboBoxModelCrearMultaIdUs, comboBoxModelCrearMultaISBN;
    private Controlador controlador;
    
    public CrearMulta(Controlador controlador) {
        this.controlador = controlador;
        comboBoxModelCrearMultaIdUs = new DefaultComboBoxModel();
        comboBoxModelCrearMultaISBN = new DefaultComboBoxModel();
        controlador.llenarComboBoxAgregarMulta(comboBoxModelCrearMultaIdUs, true);
        controlador.llenarComboBoxAgregarMulta(comboBoxModelCrearMultaISBN, false);
        initComponents();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        campoNumMulta = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        campoFecha = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        campoDescripcion = new javax.swing.JTextArea();
        botonCrearMulta = new javax.swing.JButton();
        campoValorMulta = new javax.swing.JTextField();
        jComboBox_id_usuario = new javax.swing.JComboBox<>();
        jComboBox_isbn = new javax.swing.JComboBox<>();

        setPreferredSize(new java.awt.Dimension(460, 430));

        jLabel1.setFont(new java.awt.Font("Yu Gothic", 1, 12)); // NOI18N
        jLabel1.setText("Crear Multa");

        jLabel2.setText("Valor Multa:");

        jLabel3.setText("Multa Nro:");

        campoNumMulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoNumMultaActionPerformed(evt);
            }
        });
        campoNumMulta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                campoNumMultaKeyReleased(evt);
            }
        });

        jLabel4.setText("ID Usuario:");

        jLabel5.setText("ISBN del libro:");

        jLabel6.setText("Fecha:");

        campoFecha.setForeground(new java.awt.Color(204, 204, 204));
        campoFecha.setText("\"DD-MM-YYYY\"");
        campoFecha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                campoFechaMousePressed(evt);
            }
        });
        campoFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoFechaActionPerformed(evt);
            }
        });

        jLabel7.setText("Descripcion:");

        campoDescripcion.setColumns(20);
        campoDescripcion.setRows(5);
        campoDescripcion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                campoDescripcionKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(campoDescripcion);

        botonCrearMulta.setText("Crear");
        botonCrearMulta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonCrearMultaMouseClicked(evt);
            }
        });
        botonCrearMulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCrearMultaActionPerformed(evt);
            }
        });

        campoValorMulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoValorMultaActionPerformed(evt);
            }
        });

        jComboBox_id_usuario.setModel(comboBoxModelCrearMultaIdUs);

        jComboBox_isbn.setModel(comboBoxModelCrearMultaISBN);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 103, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(campoNumMulta, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(campoValorMulta)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                                        .addComponent(campoFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jComboBox_id_usuario, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jComboBox_isbn, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(botonCrearMulta, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(39, 39, 39))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(campoNumMulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(campoFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(campoValorMulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jComboBox_id_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jComboBox_isbn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(botonCrearMulta, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void campoNumMultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoNumMultaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoNumMultaActionPerformed

    private void botonCrearMultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCrearMultaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonCrearMultaActionPerformed

    private void campoFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoFechaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoFechaActionPerformed

    private void campoValorMultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoValorMultaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoValorMultaActionPerformed

    private void campoFechaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_campoFechaMousePressed
        campoFecha.setText("");
        campoFecha.setBackground(Color.BLACK);
    }//GEN-LAST:event_campoFechaMousePressed

    private void botonCrearMultaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonCrearMultaMouseClicked
        if(jComboBox_id_usuario.getSelectedIndex() == 0 || jComboBox_isbn.getSelectedIndex() == 0){
            JOptionPane.showMessageDialog(null, "Por favor seleccione un id usuario y/o ISBN");
        }
        else{
            if(!(campoNumMulta.getText().equals("")||campoFecha.getText().equals("")||campoDescripcion.getText().equals(""))){
                String nMulta = campoNumMulta.getText();
                String date = campoFecha.getText();
                String descripcion = campoDescripcion.getText();
                if(controlador.esEntero(campoValorMulta.getText())){
                    int valor = Integer.parseInt(campoValorMulta.getText());
                    String idUsuario = (String)jComboBox_id_usuario.getSelectedItem();
                    String ISBN = (String) jComboBox_isbn.getSelectedItem();
                    Date fecha;
                    try{
                        fecha = controlador.convertirStringADate(date);
                        String numero = controlador.obtenerNEjemplarByISBNIdUsu(ISBN, idUsuario);
                        Multa multa = new Multa(nMulta, valor, fecha, descripcion, ISBN, numero, idUsuario);
                        controlador.agregarObjeto(multa);
                        JOptionPane.showMessageDialog(null, "Multa agregada con exito");
                    }
                    catch(ParseException e){
                        JOptionPane.showMessageDialog(null, "Formato de fecha no valido 'DD-MM-YYYY'");
                    }
                }
                else{
                    JOptionPane.showMessageDialog(null, "El valor para la multa debe ser un entero");
                }
            }
            else{
                JOptionPane.showMessageDialog(null, "Asegurse de llenar todos los campos");
            }
  
        }
    }//GEN-LAST:event_botonCrearMultaMouseClicked

    private void campoNumMultaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoNumMultaKeyReleased
        String size = campoNumMulta.getText();
        if(size.length()>10){
            campoNumMulta.setText("");
            JOptionPane.showMessageDialog(null, "El campo no puede tener mas de 10 caracteres");
        }
    }//GEN-LAST:event_campoNumMultaKeyReleased

    private void campoDescripcionKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoDescripcionKeyReleased
        String size = campoDescripcion.getText();
        if(size.length()>100){
            campoDescripcion.setText("");
            JOptionPane.showMessageDialog(null, "El campo no puede tener mas de 100 caracteres");
        }
    }//GEN-LAST:event_campoDescripcionKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonCrearMulta;
    private javax.swing.JTextArea campoDescripcion;
    private javax.swing.JTextField campoFecha;
    private javax.swing.JTextField campoNumMulta;
    private javax.swing.JTextField campoValorMulta;
    private javax.swing.JComboBox<String> jComboBox_id_usuario;
    private javax.swing.JComboBox<String> jComboBox_isbn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
