/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.bliblioteca.proyectobasesdedatos.GUI.Modificaciones;

import com.bliblioteca.proyectobasesdedatos.Control.Controlador;
import com.bliblioteca.proyectobasesdedatos.GUI.Crear.*;
import com.bliblioteca.proyectobasesdedatos.logica.Usuario;

/**
 *
 * @author juan.quevedo
 */
public class ModificarProfesor extends javax.swing.JPanel {

    /**
     * Creates new form Solicitud
     */
    public ModificarProfesor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        campoModificarDependenciaProfesor = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        botonModificarProfesor = new javax.swing.JButton();
        campoModificarTituloProfesor = new javax.swing.JTextField();
        labelIdUsuario = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(460, 430));

        jLabel1.setFont(new java.awt.Font("Yu Gothic", 1, 12)); // NOI18N
        jLabel1.setText("Modificar Usuario - Profesor");

        jLabel2.setText("Título:");

        jLabel4.setText("ID Usuario:");

        campoModificarDependenciaProfesor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoModificarDependenciaProfesorActionPerformed(evt);
            }
        });

        jLabel5.setText("Dependencia:");

        botonModificarProfesor.setText("Modificar");
        botonModificarProfesor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonModificarProfesorActionPerformed(evt);
            }
        });

        labelIdUsuario.setText("Id Usuario");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 251, Short.MAX_VALUE)
                        .addComponent(botonModificarProfesor, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 105, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(campoModificarDependenciaProfesor, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                            .addComponent(campoModificarTituloProfesor)
                            .addComponent(labelIdUsuario)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(39, 39, 39))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(181, 181, 181))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelIdUsuario)
                        .addGap(18, 18, 18)
                        .addComponent(campoModificarTituloProfesor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(campoModificarDependenciaProfesor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(91, 159, Short.MAX_VALUE)))
                .addComponent(botonModificarProfesor, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );
    }// </editor-fold>//GEN-END:initComponents

    private Usuario usuario;
    private Controlador controlador;
    public ModificarProfesor(Controlador controlador, Usuario usuario) {
        this.usuario = usuario;
        this.controlador = controlador;
        initComponents();

        labelIdUsuario.setText(usuario.getIdUsuario());
    }

    campoModificarTituloProfesor.addKeyListener(new java.awt.event.KeyAdapter() {
        public void keyReleased(java.awt.event.KeyEvent evt) {
            campoModificarTituloProfesorKeyListener(evt);
        }
    });

    campoModificarDependenciaProfesor.addKeyListener(new java.awt.event.KeyAdapter() {
        public void keyReleased(java.awt.event.KeyEvent evt) {
            campoModificarDependenciaProfesorKeyListener(evt);
        }
    });

    private void campoModificarDependenciaProfesorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoModificarDependenciaProfesorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoModificarDependenciaProfesorActionPerformed

    private void botonModificarProfesorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonModificarProfesorActionPerformed
        if(campoModificarTituloProfesor.getText().equals("")|| campoModificarDependenciaProfesor.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Por favor llene los campos para continuar");
        }
        else{
            String titutlo = campoModificarTituloProfesor.getText();
            String dependencia =campoModificarDependenciaProfesor.getText();
            controlador.agregarProfesor(usuario, titutlo, dependencia);
            controlador.agregarObjeto(usuario);
            JOptionPane.showMessageDialog(null, "Profesor agregado con exito");
            botonModificarProfesor.setEnabled(false);
            campoModificarDependenciaProfesor.setEnabled(false);
            campoModificarDependenciaProfesor.setEditable(false);
            campoModificarTituloProfesor.setEditable(false);
            campoModificarTituloProfesor.setEnabled(false);
        }
    }//GEN-LAST:event_botonModificarProfesorActionPerformed

    private void campoModificarTituloProfesorKeyListener(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoTituloKeyReleased
        String size = campoModificarTituloProfesor.getText();
        if(size.length()>100){
            campoModificarTituloProfesor.setText("");
            JOptionPane.showMessageDialog(null, "El campo no puede tener mas de 100 caracteres");
        }
    }//GEN-LAST:event_campoTituloKeyReleased

    private void campoModificarDependenciaProfesorKeyListener(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoDependenciaKeyReleased
        String size = campoModificarDependenciaProfesor.getText();
        if(size.length()>100){
            campoModificarDependenciaProfesor.setText("");
            JOptionPane.showMessageDialog(null, "El campo no puede tener mas de 100 caracteres");
        }
    }//GEN-LAST:event_campoDependenciaKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonModificarProfesor;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField campoModificarDependenciaProfesor;
    private javax.swing.JTextField campoModificarTituloProfesor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel labelIdUsuario;
    // End of variables declaration//GEN-END:variables
}
