/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.bliblioteca.proyectobasesdedatos.GUI.Modificaciones;

import com.bliblioteca.proyectobasesdedatos.Control.Controlador;
import com.bliblioteca.proyectobasesdedatos.DAO.DAOLibro;
import com.bliblioteca.proyectobasesdedatos.GUI.BibliotecaJFrame;
import com.bliblioteca.proyectobasesdedatos.GUI.Busquedas.BuscarLibro;
import com.bliblioteca.proyectobasesdedatos.GUI.Crear.*;
import com.bliblioteca.proyectobasesdedatos.logica.Libro;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author juan.quevedo
 */
public class ModificarLibro extends javax.swing.JPanel {

    /**
     * Creates new form Solicitud
     */
    public ModificarLibro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        campoModificarAnioPublicacion = new javax.swing.JTextField();
        campoModificarISBN = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        botonModificarLibro = new javax.swing.JButton();
        campoModificarTituloLibro = new javax.swing.JTextField();
        campoModificarNumPaginas = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        campoModificarIdioma = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();

        setPreferredSize(new java.awt.Dimension(460, 430));

        jLabel1.setFont(new java.awt.Font("Yu Gothic", 1, 12)); // NOI18N
        jLabel1.setText("Modificar Libro");

        jLabel2.setText("Titulo del libro:");

        jLabel4.setText("Año de publicación:");

        campoModificarISBN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoModificarISBNActionPerformed(evt);
            }
        });

        jLabel5.setText("ISBN del libro:");

        jLabel7.setText("Idioma:");

        botonModificarLibro.setText("Modificar");
        botonModificarLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonModificarLibroActionPerformed(evt);
            }
        });

        campoModificarTituloLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoModificarTituloLibroActionPerformed(evt);
            }
        });

        campoModificarNumPaginas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoModificarNumPaginasActionPerformed(evt);
            }
        });

        jLabel8.setText("Número de páginas:");

        campoModificarIdioma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoModificarIdiomaActionPerformed(evt);
            }
        });

        jLabel9.setText("Código de Área:");

        jLabel10.setText("Código de Editorial:");

        jComboBox1.setModel(jcbModelCodArea);

        jComboBox2.setModel(jCbModelCodEditorial);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(botonModificarLibro, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel1)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(campoModificarISBN, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                            .addComponent(campoModificarAnioPublicacion)
                            .addComponent(campoModificarTituloLibro)
                            .addComponent(campoModificarNumPaginas, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                            .addComponent(campoModificarIdioma, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                            .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(39, 39, 39))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(campoModificarTituloLibro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(campoModificarAnioPublicacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoModificarISBN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoModificarNumPaginas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoModificarIdioma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addComponent(botonModificarLibro, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );
    }// </editor-fold>//GEN-END:initComponents

    private DefaultComboBoxModel jCbModelCodEditorial,jcbModelCodArea;
    private String idEempleado;
    private Controlador controlador;
    public ModificarLibro(Controlador controlador, String idEmpleado) {
        this.idEempleado = idEmpleado;
        this.controlador = controlador;
        jCbModelCodEditorial = new DefaultComboBoxModel();
        jcbModelCodArea = new DefaultComboBoxModel();
        this.controlador.llenarComboBoxAgregarLibro(jcbModelCodArea, true);
        this.controlador.llenarComboBoxAgregarLibro(jCbModelCodEditorial, false);
        initComponents();
    }


    private void campoModificarISBNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoModificarISBNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoModificarISBNActionPerformed

    private void botonModificarLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonModificarLibroActionPerformed
        if(jComboBox1.getSelectedIndex()==0 || jComboBox2.getSelectedIndex()==0){
            JOptionPane.showMessageDialog(null, "Por favor seleccionar un campo para cod area y/o cod editorial");
        }
        else{
            if(campoModificarTituloLibro.getText().equals("")||campoModificarISBN.getText().equals("") || campoModificarNumPaginas.getText().equals("")||campoModificarIdioma.getText().equals("")){
                JOptionPane.showMessageDialog(null, "Por favor llene todos los campos");
            }
            else{
                String ISBN =campoModificarISBN.getText();
                String codArea = (String) jcbModelCodArea.getSelectedItem();
                String codEditorial = (String) jCbModelCodEditorial.getSelectedItem();
                String id_empleado = this.idEempleado;
                String tituloLibro = campoModificarTituloLibro.getText();
                if(controlador.esEntero(campoModificarNumPaginas.getText()) &&controlador.esEntero(campoModificarNumPaginas.getText())){
                    int nPaginas = Integer.parseInt((String) campoModificarNumPaginas.getText());
                    int anioPubli = Integer.parseInt((String) campoModificarAnioPublicacion.getText());
                    String idioma = campoModificarIdioma.getText();
                    Libro elLibro = new Libro(ISBN, codArea, codEditorial, id_empleado, tituloLibro, anioPubli, nPaginas, idioma);
                    DAOLibro.actualizarLibro(elLibro);
                    JOptionPane.showMessageDialog(null, "Libro modificado con exito");
                    BibliotecaJFrame.ShowPanel(new BuscarLibro(controlador, idEempleado));

                }
                else{
                    JOptionPane.showMessageDialog(null, "Numero pagianas y anio deben ser enteros");
                }
            }
        }
    }//GEN-LAST:event_botonModificarLibroActionPerformed

    private void campoModificarTituloLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoModificarTituloLibroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoModificarTituloLibroActionPerformed

    private void campoModificarNumPaginasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoModificarNumPaginasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoModificarNumPaginasActionPerformed

    private void campoModificarIdiomaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoModificarIdiomaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoModificarIdiomaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonModificarLibro;
    private javax.swing.JTextField campoModificarAnioPublicacion;
    private javax.swing.JTextField campoModificarISBN;
    private javax.swing.JTextField campoModificarIdioma;
    private javax.swing.JTextField campoModificarNumPaginas;
    private javax.swing.JTextField campoModificarTituloLibro;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
