/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.bliblioteca.proyectobasesdedatos.GUI.Busquedas;

import com.bliblioteca.proyectobasesdedatos.Control.Controlador;
import com.bliblioteca.proyectobasesdedatos.GUI.BibliotecaJFrame;
import com.bliblioteca.proyectobasesdedatos.GUI.Crear.*;
import com.bliblioteca.proyectobasesdedatos.GUI.Modificaciones.ModificarMulta;
import com.bliblioteca.proyectobasesdedatos.GUI.Modificaciones.ModificarPrestamo;
import com.bliblioteca.proyectobasesdedatos.logica.Prestamo;
import com.bliblioteca.proyectobasesdedatos.logica.Solicitud;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author juan.quevedo
 */
public class BuscarPrestamo extends javax.swing.JPanel {

    /**
     * Creates new form Solicitud
     */
    private DefaultComboBoxModel comboBoxModelBuscarPrestamo;
    private DefaultTableModel tableModel;
    private Controlador controlador;
    private String idEmpleado;
    public BuscarPrestamo(Controlador controlador, String idEmpleado) {
        this.idEmpleado = idEmpleado;
        this.controlador =controlador;
        comboBoxModelBuscarPrestamo = new DefaultComboBoxModel();
        tableModel = new DefaultTableModel();
        controlador.llenarComboBoxBuscarPrestamo(comboBoxModelBuscarPrestamo);
        controlador.llenarTablaBuscarPrestamo(tableModel);
        Object[] columnas = {"N_PRESTAMO","FECHA_R", "FECHA_D","ID_USUARIO","ID_EMPLEADO","ISBN", "NUMERO"};
        tableModel.setColumnIdentifiers(columnas);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        botonEditarPrestamo = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        botonBuscarPrestamo = new javax.swing.JButton();
        botonEliminarPrestamo = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(460, 430));

        jLabel1.setFont(new java.awt.Font("Yu Gothic", 1, 12)); // NOI18N
        jLabel1.setText("Buscar Prestamo");

        jLabel2.setText("Número de Prestamo:");

        botonEditarPrestamo.setText("Editar");
        botonEditarPrestamo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonEditarPrestamoMouseClicked(evt);
            }
        });
        botonEditarPrestamo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEditarPrestamoActionPerformed(evt);
            }
        });

        jTable1.setModel(tableModel);
        jScrollPane1.setViewportView(jTable1);

        botonBuscarPrestamo.setText("Buscar");
        botonBuscarPrestamo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonBuscarPrestamoMouseClicked(evt);
            }
        });
        botonBuscarPrestamo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBuscarPrestamoActionPerformed(evt);
            }
        });

        botonEliminarPrestamo.setText("Eliminar");
        botonEliminarPrestamo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonEliminarPrestamoMouseClicked(evt);
            }
        });
        botonEliminarPrestamo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEliminarPrestamoActionPerformed(evt);
            }
        });

        jComboBox1.setModel(comboBoxModelBuscarPrestamo);

        jButton1.setText("Mostrar todos");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(botonEditarPrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botonEliminarPrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(jComboBox1, 0, 126, Short.MAX_VALUE))
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(botonBuscarPrestamo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1)
                        .addGap(16, 16, 16)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonBuscarPrestamo)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonEditarPrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonEliminarPrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void botonEditarPrestamoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEditarPrestamoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonEditarPrestamoActionPerformed

    private void botonBuscarPrestamoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBuscarPrestamoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonBuscarPrestamoActionPerformed

    private void botonEliminarPrestamoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminarPrestamoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonEliminarPrestamoActionPerformed

    private void botonBuscarPrestamoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonBuscarPrestamoMouseClicked
        if(jComboBox1.getSelectedIndex() == 0){
            JOptionPane.showMessageDialog(null, "Por favor seleccione un numero de solicitud");
        }
        else{
            String numPrestamo = (String) jComboBox1.getSelectedItem();
            Prestamo solicitudEncontrada = controlador.buscarPrestamo(numPrestamo);
            Object[] filas = new Object[7];
            tableModel.setRowCount(0);
            filas[0] = solicitudEncontrada.getnPrestamo();
            filas[1] = solicitudEncontrada.getFechaR();
            filas[2] = solicitudEncontrada.getFechaD();
            filas[3] = solicitudEncontrada.getIdUsuario();
            filas[4] = solicitudEncontrada.getIdEmpleado();
            filas[5] = solicitudEncontrada.getISBN();
            filas[6] = solicitudEncontrada.getNumero();
            tableModel.addRow(filas);
            
        }
    }//GEN-LAST:event_botonBuscarPrestamoMouseClicked

    private void botonEliminarPrestamoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonEliminarPrestamoMouseClicked
        int filaSeleccionada = jTable1.getSelectedRow();
        if(jTable1.getSelectedRow()==-1){
            JOptionPane.showMessageDialog(null,"Seleccione una fila de la tabla...");
            
        }
        else if(jTable1.getSelectedRows().length >1){
            JOptionPane.showMessageDialog(null,"Seleccione SOLO UNA fila...");
        }
        else{
            int columnas = jTable1.getColumnCount();
            Object[] valores = new Object[columnas];

            for (int columna = 0; columna < columnas; columna++) {
                valores[columna] = jTable1.getValueAt(filaSeleccionada, columna);
            }

            
            Prestamo solicitudAEliminar = new Prestamo();
            solicitudAEliminar.setnPrestamo((String)valores[0]);
            try{
                controlador.eliminarObjeto(solicitudAEliminar);
                JOptionPane.showMessageDialog(null, "PRESTAMO ELIMINADO");
            }
            catch(UnsupportedOperationException e){
                JOptionPane.showMessageDialog(null, e.getMessage());
            }
        }
    }//GEN-LAST:event_botonEliminarPrestamoMouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        controlador.llenarTablaBuscarPrestamo(tableModel);
        
    }//GEN-LAST:event_jButton1MouseClicked

    private void botonEditarPrestamoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonEditarPrestamoMouseClicked
        BibliotecaJFrame.ShowPanel(new ModificarPrestamo(controlador, idEmpleado));
    }//GEN-LAST:event_botonEditarPrestamoMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonBuscarPrestamo;
    private javax.swing.JButton botonEditarPrestamo;
    private javax.swing.JButton botonEliminarPrestamo;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
